// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/zkid/v1/zkid.proto

package zkidv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChallengeRequest) Reset() {
	*x = CreateChallengeRequest{}
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChallengeRequest) ProtoMessage() {}

func (x *CreateChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChallengeRequest.ProtoReflect.Descriptor instead.
func (*CreateChallengeRequest) Descriptor() ([]byte, []int) {
	return file_proto_zkid_v1_zkid_proto_rawDescGZIP(), []int{0}
}

type CreateChallengeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Per-session challenge field element (decimal). Bound into the device-sig
	// proof via a Semaphore-style dummy square; submitted back at /link-verify.
	Challenge string `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	// Application's stable APP_ID, 62-char lowercase hex.
	AppId         string `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ExpiresAt     string `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChallengeResponse) Reset() {
	*x = CreateChallengeResponse{}
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChallengeResponse) ProtoMessage() {}

func (x *CreateChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChallengeResponse.ProtoReflect.Descriptor instead.
func (*CreateChallengeResponse) Descriptor() ([]byte, []int) {
	return file_proto_zkid_v1_zkid_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChallengeResponse) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *CreateChallengeResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CreateChallengeResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type GetChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     string                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChallengeRequest) Reset() {
	*x = GetChallengeRequest{}
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeRequest) ProtoMessage() {}

func (x *GetChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeRequest.ProtoReflect.Descriptor instead.
func (*GetChallengeRequest) Descriptor() ([]byte, []int) {
	return file_proto_zkid_v1_zkid_proto_rawDescGZIP(), []int{2}
}

func (x *GetChallengeRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

type GetChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     string                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChallengeResponse) Reset() {
	*x = GetChallengeResponse{}
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeResponse) ProtoMessage() {}

func (x *GetChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeResponse.ProtoReflect.Descriptor instead.
func (*GetChallengeResponse) Descriptor() ([]byte, []int) {
	return file_proto_zkid_v1_zkid_proto_rawDescGZIP(), []int{3}
}

func (x *GetChallengeResponse) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *GetChallengeResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetChallengeResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type LinkVerifyRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Challenge string                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	// "rs2048" (default) or "rs4096"
	CertChainType string `protobuf:"bytes,2,opt,name=cert_chain_type,json=certChainType,proto3" json:"cert_chain_type,omitempty"`
	// Binary proof data (no base64 needed in gRPC)
	CertChainProof []byte `protobuf:"bytes,3,opt,name=cert_chain_proof,json=certChainProof,proto3" json:"cert_chain_proof,omitempty"`
	UserSigProof   []byte `protobuf:"bytes,4,opt,name=user_sig_proof,json=userSigProof,proto3" json:"user_sig_proof,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LinkVerifyRequest) Reset() {
	*x = LinkVerifyRequest{}
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkVerifyRequest) ProtoMessage() {}

func (x *LinkVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkVerifyRequest.ProtoReflect.Descriptor instead.
func (*LinkVerifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_zkid_v1_zkid_proto_rawDescGZIP(), []int{4}
}

func (x *LinkVerifyRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *LinkVerifyRequest) GetCertChainType() string {
	if x != nil {
		return x.CertChainType
	}
	return ""
}

func (x *LinkVerifyRequest) GetCertChainProof() []byte {
	if x != nil {
		return x.CertChainProof
	}
	return nil
}

func (x *LinkVerifyRequest) GetUserSigProof() []byte {
	if x != nil {
		return x.UserSigProof
	}
	return nil
}

type LinkVerifyResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Verified   bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	Nullifier  string                 `protobuf:"bytes,2,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
	IdVerified bool                   `protobuf:"varint,3,opt,name=id_verified,json=idVerified,proto3" json:"id_verified,omitempty"`
	Persisted  bool                   `protobuf:"varint,4,opt,name=persisted,proto3" json:"persisted,omitempty"`
	Error      string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	// "proof_invalid", "smt_root_mismatch", "issuer_modulus_mismatch",
	// "app_id_mismatch", or "challenge_mismatch"; empty when verified=true.
	Reason string `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	// Populated when SMT root enforcement ran; unset when SMT_ROOT_ENFORCE=disabled.
	SmtRoot *SmtRootOutcome `protobuf:"bytes,7,opt,name=smt_root,json=smtRoot,proto3" json:"smt_root,omitempty"`
	// Populated when issuer-cert enforcement ran; unset when ISSUER_CERT_ENFORCE=disabled.
	IssuerModulus *IssuerModulusOutcome `protobuf:"bytes,8,opt,name=issuer_modulus,json=issuerModulus,proto3" json:"issuer_modulus,omitempty"`
	// Populated when ExpectedAppID is configured.
	AppId *AppIDOutcome `protobuf:"bytes,9,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Populated when the per-session challenge check ran (i.e. the stored
	// challenge value is non-empty).
	Challenge     *ChallengeOutcome `protobuf:"bytes,10,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkVerifyResponse) Reset() {
	*x = LinkVerifyResponse{}
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkVerifyResponse) ProtoMessage() {}

func (x *LinkVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkVerifyResponse.ProtoReflect.Descriptor instead.
func (*LinkVerifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_zkid_v1_zkid_proto_rawDescGZIP(), []int{5}
}

func (x *LinkVerifyResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *LinkVerifyResponse) GetNullifier() string {
	if x != nil {
		return x.Nullifier
	}
	return ""
}

func (x *LinkVerifyResponse) GetIdVerified() bool {
	if x != nil {
		return x.IdVerified
	}
	return false
}

func (x *LinkVerifyResponse) GetPersisted() bool {
	if x != nil {
		return x.Persisted
	}
	return false
}

func (x *LinkVerifyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LinkVerifyResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *LinkVerifyResponse) GetSmtRoot() *SmtRootOutcome {
	if x != nil {
		return x.SmtRoot
	}
	return nil
}

func (x *LinkVerifyResponse) GetIssuerModulus() *IssuerModulusOutcome {
	if x != nil {
		return x.IssuerModulus
	}
	return nil
}

func (x *LinkVerifyResponse) GetAppId() *AppIDOutcome {
	if x != nil {
		return x.AppId
	}
	return nil
}

func (x *LinkVerifyResponse) GetChallenge() *ChallengeOutcome {
	if x != nil {
		return x.Challenge
	}
	return nil
}

type SmtRootOutcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "g2" or "g3", derived from cert_chain_type.
	Issuer string `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Match  bool   `protobuf:"varint,2,opt,name=match,proto3" json:"match,omitempty"`
	// 0x-prefixed, lower-case, 32-byte hex.
	Expected string `protobuf:"bytes,3,opt,name=expected,proto3" json:"expected,omitempty"`
	Observed string `protobuf:"bytes,4,opt,name=observed,proto3" json:"observed,omitempty"`
	// "onchain", "github", or "static".
	TrustSource string `protobuf:"bytes,5,opt,name=trust_source,json=trustSource,proto3" json:"trust_source,omitempty"`
	// RFC3339 timestamp of the last successful refresh.
	TrustedAt     string `protobuf:"bytes,6,opt,name=trusted_at,json=trustedAt,proto3" json:"trusted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmtRootOutcome) Reset() {
	*x = SmtRootOutcome{}
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmtRootOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmtRootOutcome) ProtoMessage() {}

func (x *SmtRootOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmtRootOutcome.ProtoReflect.Descriptor instead.
func (*SmtRootOutcome) Descriptor() ([]byte, []int) {
	return file_proto_zkid_v1_zkid_proto_rawDescGZIP(), []int{6}
}

func (x *SmtRootOutcome) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *SmtRootOutcome) GetMatch() bool {
	if x != nil {
		return x.Match
	}
	return false
}

func (x *SmtRootOutcome) GetExpected() string {
	if x != nil {
		return x.Expected
	}
	return ""
}

func (x *SmtRootOutcome) GetObserved() string {
	if x != nil {
		return x.Observed
	}
	return ""
}

func (x *SmtRootOutcome) GetTrustSource() string {
	if x != nil {
		return x.TrustSource
	}
	return ""
}

func (x *SmtRootOutcome) GetTrustedAt() string {
	if x != nil {
		return x.TrustedAt
	}
	return ""
}

type IssuerModulusOutcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "g2" or "g3", derived from cert_chain_type.
	Issuer string `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Match  bool   `protobuf:"varint,2,opt,name=match,proto3" json:"match,omitempty"`
	// 0x-prefixed SHA-256 of the trusted MOICA cert DER.
	ExpectedSha256 string `protobuf:"bytes,3,opt,name=expected_sha256,json=expectedSha256,proto3" json:"expected_sha256,omitempty"`
	// "embedded" or "https".
	TrustSource string `protobuf:"bytes,4,opt,name=trust_source,json=trustSource,proto3" json:"trust_source,omitempty"`
	// RFC3339 timestamp of the last cache update.
	TrustedAt     string `protobuf:"bytes,5,opt,name=trusted_at,json=trustedAt,proto3" json:"trusted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuerModulusOutcome) Reset() {
	*x = IssuerModulusOutcome{}
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuerModulusOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuerModulusOutcome) ProtoMessage() {}

func (x *IssuerModulusOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuerModulusOutcome.ProtoReflect.Descriptor instead.
func (*IssuerModulusOutcome) Descriptor() ([]byte, []int) {
	return file_proto_zkid_v1_zkid_proto_rawDescGZIP(), []int{7}
}

func (x *IssuerModulusOutcome) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *IssuerModulusOutcome) GetMatch() bool {
	if x != nil {
		return x.Match
	}
	return false
}

func (x *IssuerModulusOutcome) GetExpectedSha256() string {
	if x != nil {
		return x.ExpectedSha256
	}
	return ""
}

func (x *IssuerModulusOutcome) GetTrustSource() string {
	if x != nil {
		return x.TrustSource
	}
	return ""
}

func (x *IssuerModulusOutcome) GetTrustedAt() string {
	if x != nil {
		return x.TrustedAt
	}
	return ""
}

type AppIDOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         bool                   `protobuf:"varint,1,opt,name=match,proto3" json:"match,omitempty"`
	Expected      string                 `protobuf:"bytes,2,opt,name=expected,proto3" json:"expected,omitempty"`
	Observed      string                 `protobuf:"bytes,3,opt,name=observed,proto3" json:"observed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppIDOutcome) Reset() {
	*x = AppIDOutcome{}
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppIDOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppIDOutcome) ProtoMessage() {}

func (x *AppIDOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppIDOutcome.ProtoReflect.Descriptor instead.
func (*AppIDOutcome) Descriptor() ([]byte, []int) {
	return file_proto_zkid_v1_zkid_proto_rawDescGZIP(), []int{8}
}

func (x *AppIDOutcome) GetMatch() bool {
	if x != nil {
		return x.Match
	}
	return false
}

func (x *AppIDOutcome) GetExpected() string {
	if x != nil {
		return x.Expected
	}
	return ""
}

func (x *AppIDOutcome) GetObserved() string {
	if x != nil {
		return x.Observed
	}
	return ""
}

type ChallengeOutcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Match bool                   `protobuf:"varint,1,opt,name=match,proto3" json:"match,omitempty"`
	// Decimal field-element strings (per-session challenge value).
	Expected      string `protobuf:"bytes,2,opt,name=expected,proto3" json:"expected,omitempty"`
	Observed      string `protobuf:"bytes,3,opt,name=observed,proto3" json:"observed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeOutcome) Reset() {
	*x = ChallengeOutcome{}
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeOutcome) ProtoMessage() {}

func (x *ChallengeOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zkid_v1_zkid_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeOutcome.ProtoReflect.Descriptor instead.
func (*ChallengeOutcome) Descriptor() ([]byte, []int) {
	return file_proto_zkid_v1_zkid_proto_rawDescGZIP(), []int{9}
}

func (x *ChallengeOutcome) GetMatch() bool {
	if x != nil {
		return x.Match
	}
	return false
}

func (x *ChallengeOutcome) GetExpected() string {
	if x != nil {
		return x.Expected
	}
	return ""
}

func (x *ChallengeOutcome) GetObserved() string {
	if x != nil {
		return x.Observed
	}
	return ""
}

var File_proto_zkid_v1_zkid_proto protoreflect.FileDescriptor

const file_proto_zkid_v1_zkid_proto_rawDesc = "" +
	"\n" +
	"\x18proto/zkid/v1/zkid.proto\x12\azkid.v1\"\x18\n" +
	"\x16CreateChallengeRequest\"m\n" +
	"\x17CreateChallengeResponse\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\tR\tchallenge\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"3\n" +
	"\x13GetChallengeRequest\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\tR\tchallenge\"j\n" +
	"\x14GetChallengeResponse\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\tR\tchallenge\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"\xa9\x01\n" +
	"\x11LinkVerifyRequest\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\tR\tchallenge\x12&\n" +
	"\x0fcert_chain_type\x18\x02 \x01(\tR\rcertChainType\x12(\n" +
	"\x10cert_chain_proof\x18\x03 \x01(\fR\x0ecertChainProof\x12$\n" +
	"\x0euser_sig_proof\x18\x04 \x01(\fR\fuserSigProof\"\x9c\x03\n" +
	"\x12LinkVerifyResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12\x1c\n" +
	"\tnullifier\x18\x02 \x01(\tR\tnullifier\x12\x1f\n" +
	"\vid_verified\x18\x03 \x01(\bR\n" +
	"idVerified\x12\x1c\n" +
	"\tpersisted\x18\x04 \x01(\bR\tpersisted\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x122\n" +
	"\bsmt_root\x18\a \x01(\v2\x17.zkid.v1.SmtRootOutcomeR\asmtRoot\x12D\n" +
	"\x0eissuer_modulus\x18\b \x01(\v2\x1d.zkid.v1.IssuerModulusOutcomeR\rissuerModulus\x12,\n" +
	"\x06app_id\x18\t \x01(\v2\x15.zkid.v1.AppIDOutcomeR\x05appId\x127\n" +
	"\tchallenge\x18\n" +
	" \x01(\v2\x19.zkid.v1.ChallengeOutcomeR\tchallenge\"\xb8\x01\n" +
	"\x0eSmtRootOutcome\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12\x14\n" +
	"\x05match\x18\x02 \x01(\bR\x05match\x12\x1a\n" +
	"\bexpected\x18\x03 \x01(\tR\bexpected\x12\x1a\n" +
	"\bobserved\x18\x04 \x01(\tR\bobserved\x12!\n" +
	"\ftrust_source\x18\x05 \x01(\tR\vtrustSource\x12\x1d\n" +
	"\n" +
	"trusted_at\x18\x06 \x01(\tR\ttrustedAt\"\xaf\x01\n" +
	"\x14IssuerModulusOutcome\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12\x14\n" +
	"\x05match\x18\x02 \x01(\bR\x05match\x12'\n" +
	"\x0fexpected_sha256\x18\x03 \x01(\tR\x0eexpectedSha256\x12!\n" +
	"\ftrust_source\x18\x04 \x01(\tR\vtrustSource\x12\x1d\n" +
	"\n" +
	"trusted_at\x18\x05 \x01(\tR\ttrustedAt\"\\\n" +
	"\fAppIDOutcome\x12\x14\n" +
	"\x05match\x18\x01 \x01(\bR\x05match\x12\x1a\n" +
	"\bexpected\x18\x02 \x01(\tR\bexpected\x12\x1a\n" +
	"\bobserved\x18\x03 \x01(\tR\bobserved\"`\n" +
	"\x10ChallengeOutcome\x12\x14\n" +
	"\x05match\x18\x01 \x01(\bR\x05match\x12\x1a\n" +
	"\bexpected\x18\x02 \x01(\tR\bexpected\x12\x1a\n" +
	"\bobserved\x18\x03 \x01(\tR\bobserved2\xf8\x01\n" +
	"\fZkIDVerifier\x12T\n" +
	"\x0fCreateChallenge\x12\x1f.zkid.v1.CreateChallengeRequest\x1a .zkid.v1.CreateChallengeResponse\x12K\n" +
	"\fGetChallenge\x12\x1c.zkid.v1.GetChallengeRequest\x1a\x1d.zkid.v1.GetChallengeResponse\x12E\n" +
	"\n" +
	"LinkVerify\x12\x1a.zkid.v1.LinkVerifyRequest\x1a\x1b.zkid.v1.LinkVerifyResponseBCZAgithub.com/privacy-ethereum/go-zkid-verifier/proto/zkid/v1;zkidv1b\x06proto3"

var (
	file_proto_zkid_v1_zkid_proto_rawDescOnce sync.Once
	file_proto_zkid_v1_zkid_proto_rawDescData []byte
)

func file_proto_zkid_v1_zkid_proto_rawDescGZIP() []byte {
	file_proto_zkid_v1_zkid_proto_rawDescOnce.Do(func() {
		file_proto_zkid_v1_zkid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_zkid_v1_zkid_proto_rawDesc), len(file_proto_zkid_v1_zkid_proto_rawDesc)))
	})
	return file_proto_zkid_v1_zkid_proto_rawDescData
}

var file_proto_zkid_v1_zkid_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_zkid_v1_zkid_proto_goTypes = []any{
	(*CreateChallengeRequest)(nil),  // 0: zkid.v1.CreateChallengeRequest
	(*CreateChallengeResponse)(nil), // 1: zkid.v1.CreateChallengeResponse
	(*GetChallengeRequest)(nil),     // 2: zkid.v1.GetChallengeRequest
	(*GetChallengeResponse)(nil),    // 3: zkid.v1.GetChallengeResponse
	(*LinkVerifyRequest)(nil),       // 4: zkid.v1.LinkVerifyRequest
	(*LinkVerifyResponse)(nil),      // 5: zkid.v1.LinkVerifyResponse
	(*SmtRootOutcome)(nil),          // 6: zkid.v1.SmtRootOutcome
	(*IssuerModulusOutcome)(nil),    // 7: zkid.v1.IssuerModulusOutcome
	(*AppIDOutcome)(nil),            // 8: zkid.v1.AppIDOutcome
	(*ChallengeOutcome)(nil),        // 9: zkid.v1.ChallengeOutcome
}
var file_proto_zkid_v1_zkid_proto_depIdxs = []int32{
	6, // 0: zkid.v1.LinkVerifyResponse.smt_root:type_name -> zkid.v1.SmtRootOutcome
	7, // 1: zkid.v1.LinkVerifyResponse.issuer_modulus:type_name -> zkid.v1.IssuerModulusOutcome
	8, // 2: zkid.v1.LinkVerifyResponse.app_id:type_name -> zkid.v1.AppIDOutcome
	9, // 3: zkid.v1.LinkVerifyResponse.challenge:type_name -> zkid.v1.ChallengeOutcome
	0, // 4: zkid.v1.ZkIDVerifier.CreateChallenge:input_type -> zkid.v1.CreateChallengeRequest
	2, // 5: zkid.v1.ZkIDVerifier.GetChallenge:input_type -> zkid.v1.GetChallengeRequest
	4, // 6: zkid.v1.ZkIDVerifier.LinkVerify:input_type -> zkid.v1.LinkVerifyRequest
	1, // 7: zkid.v1.ZkIDVerifier.CreateChallenge:output_type -> zkid.v1.CreateChallengeResponse
	3, // 8: zkid.v1.ZkIDVerifier.GetChallenge:output_type -> zkid.v1.GetChallengeResponse
	5, // 9: zkid.v1.ZkIDVerifier.LinkVerify:output_type -> zkid.v1.LinkVerifyResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_zkid_v1_zkid_proto_init() }
func file_proto_zkid_v1_zkid_proto_init() {
	if File_proto_zkid_v1_zkid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_zkid_v1_zkid_proto_rawDesc), len(file_proto_zkid_v1_zkid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_zkid_v1_zkid_proto_goTypes,
		DependencyIndexes: file_proto_zkid_v1_zkid_proto_depIdxs,
		MessageInfos:      file_proto_zkid_v1_zkid_proto_msgTypes,
	}.Build()
	File_proto_zkid_v1_zkid_proto = out.File
	file_proto_zkid_v1_zkid_proto_goTypes = nil
	file_proto_zkid_v1_zkid_proto_depIdxs = nil
}
