// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.0
// source: proto/zkid/v1/zkid.proto

package zkidv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZkIDVerifier_CreateChallenge_FullMethodName       = "/zkid.v1.ZkIDVerifier/CreateChallenge"
	ZkIDVerifier_GetChallenge_FullMethodName          = "/zkid.v1.ZkIDVerifier/GetChallenge"
	ZkIDVerifier_LinkVerify_FullMethodName            = "/zkid.v1.ZkIDVerifier/LinkVerify"
	ZkIDVerifier_VerifyTBS_FullMethodName             = "/zkid.v1.ZkIDVerifier/VerifyTBS"
	ZkIDVerifier_GetVerificationStatus_FullMethodName = "/zkid.v1.ZkIDVerifier/GetVerificationStatus"
)

// ZkIDVerifierClient is the client API for ZkIDVerifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZkIDVerifierClient interface {
	// CreateChallenge generates a new challenge nonce for ZK verification.
	CreateChallenge(ctx context.Context, in *CreateChallengeRequest, opts ...grpc.CallOption) (*CreateChallengeResponse, error)
	// GetChallenge retrieves a challenge by ID.
	GetChallenge(ctx context.Context, in *GetChallengeRequest, opts ...grpc.CallOption) (*GetChallengeResponse, error)
	// LinkVerify verifies cert-chain and device-sig proofs with pk_commit linkage.
	LinkVerify(ctx context.Context, in *LinkVerifyRequest, opts ...grpc.CallOption) (*LinkVerifyResponse, error)
	// VerifyTBS verifies a TBS hash against a challenge (legacy endpoint).
	VerifyTBS(ctx context.Context, in *VerifyTBSRequest, opts ...grpc.CallOption) (*VerifyTBSResponse, error)
	// GetVerificationStatus retrieves verification status by nullifier.
	GetVerificationStatus(ctx context.Context, in *GetVerificationStatusRequest, opts ...grpc.CallOption) (*GetVerificationStatusResponse, error)
}

type zkIDVerifierClient struct {
	cc grpc.ClientConnInterface
}

func NewZkIDVerifierClient(cc grpc.ClientConnInterface) ZkIDVerifierClient {
	return &zkIDVerifierClient{cc}
}

func (c *zkIDVerifierClient) CreateChallenge(ctx context.Context, in *CreateChallengeRequest, opts ...grpc.CallOption) (*CreateChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateChallengeResponse)
	err := c.cc.Invoke(ctx, ZkIDVerifier_CreateChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zkIDVerifierClient) GetChallenge(ctx context.Context, in *GetChallengeRequest, opts ...grpc.CallOption) (*GetChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChallengeResponse)
	err := c.cc.Invoke(ctx, ZkIDVerifier_GetChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zkIDVerifierClient) LinkVerify(ctx context.Context, in *LinkVerifyRequest, opts ...grpc.CallOption) (*LinkVerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkVerifyResponse)
	err := c.cc.Invoke(ctx, ZkIDVerifier_LinkVerify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zkIDVerifierClient) VerifyTBS(ctx context.Context, in *VerifyTBSRequest, opts ...grpc.CallOption) (*VerifyTBSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyTBSResponse)
	err := c.cc.Invoke(ctx, ZkIDVerifier_VerifyTBS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zkIDVerifierClient) GetVerificationStatus(ctx context.Context, in *GetVerificationStatusRequest, opts ...grpc.CallOption) (*GetVerificationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVerificationStatusResponse)
	err := c.cc.Invoke(ctx, ZkIDVerifier_GetVerificationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZkIDVerifierServer is the server API for ZkIDVerifier service.
// All implementations must embed UnimplementedZkIDVerifierServer
// for forward compatibility.
type ZkIDVerifierServer interface {
	// CreateChallenge generates a new challenge nonce for ZK verification.
	CreateChallenge(context.Context, *CreateChallengeRequest) (*CreateChallengeResponse, error)
	// GetChallenge retrieves a challenge by ID.
	GetChallenge(context.Context, *GetChallengeRequest) (*GetChallengeResponse, error)
	// LinkVerify verifies cert-chain and device-sig proofs with pk_commit linkage.
	LinkVerify(context.Context, *LinkVerifyRequest) (*LinkVerifyResponse, error)
	// VerifyTBS verifies a TBS hash against a challenge (legacy endpoint).
	VerifyTBS(context.Context, *VerifyTBSRequest) (*VerifyTBSResponse, error)
	// GetVerificationStatus retrieves verification status by nullifier.
	GetVerificationStatus(context.Context, *GetVerificationStatusRequest) (*GetVerificationStatusResponse, error)
	mustEmbedUnimplementedZkIDVerifierServer()
}

// UnimplementedZkIDVerifierServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZkIDVerifierServer struct{}

func (UnimplementedZkIDVerifierServer) CreateChallenge(context.Context, *CreateChallengeRequest) (*CreateChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChallenge not implemented")
}
func (UnimplementedZkIDVerifierServer) GetChallenge(context.Context, *GetChallengeRequest) (*GetChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChallenge not implemented")
}
func (UnimplementedZkIDVerifierServer) LinkVerify(context.Context, *LinkVerifyRequest) (*LinkVerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkVerify not implemented")
}
func (UnimplementedZkIDVerifierServer) VerifyTBS(context.Context, *VerifyTBSRequest) (*VerifyTBSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyTBS not implemented")
}
func (UnimplementedZkIDVerifierServer) GetVerificationStatus(context.Context, *GetVerificationStatusRequest) (*GetVerificationStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVerificationStatus not implemented")
}
func (UnimplementedZkIDVerifierServer) mustEmbedUnimplementedZkIDVerifierServer() {}
func (UnimplementedZkIDVerifierServer) testEmbeddedByValue()                      {}

// UnsafeZkIDVerifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZkIDVerifierServer will
// result in compilation errors.
type UnsafeZkIDVerifierServer interface {
	mustEmbedUnimplementedZkIDVerifierServer()
}

func RegisterZkIDVerifierServer(s grpc.ServiceRegistrar, srv ZkIDVerifierServer) {
	// If the following call panics, it indicates UnimplementedZkIDVerifierServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZkIDVerifier_ServiceDesc, srv)
}

func _ZkIDVerifier_CreateChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZkIDVerifierServer).CreateChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZkIDVerifier_CreateChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZkIDVerifierServer).CreateChallenge(ctx, req.(*CreateChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZkIDVerifier_GetChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZkIDVerifierServer).GetChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZkIDVerifier_GetChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZkIDVerifierServer).GetChallenge(ctx, req.(*GetChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZkIDVerifier_LinkVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZkIDVerifierServer).LinkVerify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZkIDVerifier_LinkVerify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZkIDVerifierServer).LinkVerify(ctx, req.(*LinkVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZkIDVerifier_VerifyTBS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTBSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZkIDVerifierServer).VerifyTBS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZkIDVerifier_VerifyTBS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZkIDVerifierServer).VerifyTBS(ctx, req.(*VerifyTBSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZkIDVerifier_GetVerificationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVerificationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZkIDVerifierServer).GetVerificationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZkIDVerifier_GetVerificationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZkIDVerifierServer).GetVerificationStatus(ctx, req.(*GetVerificationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZkIDVerifier_ServiceDesc is the grpc.ServiceDesc for ZkIDVerifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZkIDVerifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zkid.v1.ZkIDVerifier",
	HandlerType: (*ZkIDVerifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChallenge",
			Handler:    _ZkIDVerifier_CreateChallenge_Handler,
		},
		{
			MethodName: "GetChallenge",
			Handler:    _ZkIDVerifier_GetChallenge_Handler,
		},
		{
			MethodName: "LinkVerify",
			Handler:    _ZkIDVerifier_LinkVerify_Handler,
		},
		{
			MethodName: "VerifyTBS",
			Handler:    _ZkIDVerifier_VerifyTBS_Handler,
		},
		{
			MethodName: "GetVerificationStatus",
			Handler:    _ZkIDVerifier_GetVerificationStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/zkid/v1/zkid.proto",
}
